### DISCUSSION TITLE
Azure Devops Pipeline - user input

### DISCUSSION THREAD

**Discussion by po-wehi** [AzureCommunityPL/group#254] [Pomoc]
Hej,

Mam problem - proboje przeniesc pipeline z Jenkinsa na Azure Devops ale zderzylem sie ze sciana.

W jenkinskie odpala sie pipeline i sprawdza jakie pliki znajduja sie w katalogu A. Pliki te nastepnie sa generowane jako lista i user w trakcie deploymentu ma mozliwosc wyboru ktory plik wybrac.

Nie bardzo wiem jak to ugryźć w Azure...:-(

Nie widzę nawet możliwości User Inputu tzn. zeby w trakcie deploymentu wyskoczylo okienko z podaniem jakiejs wartosci, ktora nastepnie bedzie procesowana.

Czy ktos wie jak mi pomoc w tym temacie? Bede wdzieczny za jakiekolwiek wskazowki !

**Comment by ptrstpp950** [comment]
To się nazywa parameters i w YAML może wyglądać tak:
```
parameters:
- name: Environment
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - uat
  - perf
```

Wtedy podczas uruchomienia możesz go w okienku wybrać tak samo jak branch
