### DISCUSSION TITLE
[AKS] Sterowanie ruchem wychodzącym (pub ip)

### DISCUSSION THREAD

**Discussion by galibozek** [AzureCommunityPL/group#347] [Pomoc]
Witam, czy jest możliwość sterowania ruchem wychodzącym per pod/deployment/? - na jaki adres jest nat? 
Chciałbym dla konkretnych usług ustawić jeden statyczny adres, a dla innych kilka i sterować nimi, jest to do osiągnięcia? 

w ramach jedno klastra

EDIT:

głównie chodzi mi o sytuacje kiedy to pod nawiązuje połączenie do usługi zewnętrznej

CNI: Calico

**Comment by ptrstpp950** [comment]
Jeżeli potrzebujesz statycznego adresu IP (acz on nie do końca jest znany z góry) to potrzebujesz Egress z Azure Load Balancer (https://docs.microsoft.com/en-us/azure/aks/egress)
Co posiadania kilku to jest to problem, ale może ktoś kojarzy obejście na samym AKS, bo innym rozwiązaniem jest postawienie czegoś na zewnątrz

**Reply by galibozek** [reply]
Nie działa mi to, już kiedyś to sprawdzałem, być może działa przy konkretnej konfiguracji sieci.
Udało Ci się to uruchomić aby działało? mając kilka adresów?

**Reply by ptrstpp950** [reply]
Działało mi tylko wtedy kiedy miałem jeden adres wychodzący, a nie kilka. Jak potrzebowałem kilku to stawiałem "pośrednika"

**Reply by galibozek** [reply]
mówiąc "pośrednika" co masz na myśli?

**Comment by mmisztal1980** [comment]
@galibozek popatrzyłbym,czy [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) nie rozwiązuje Twojego problemu.

- Wiele usług za 1 adresem: Postaw jakiś API gateway wewnętrznie i niech on rozkminia routing do docelowych usług
- Wiele usług wiele adresów: Możesz definiować obiekty `Service` w dowolnej ilości, dodatkowo możesz "ręcznie" definiować endpointy jeżeli chciałbyś w 100% kontrolować co za danym serwisem się kryje 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - name: tcp-port
    port: 9092
    targetPort: 9092
    protocol: TCP

---

kind: Endpoints
apiVersion: v1
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: "172.19.13.12"
      - ip: "172.19.13.13"
      - ip: "172.19.13.9"
    ports:
      - name: my-service
        port: 9092
```

- Totalna kontrola nad ruchem wychodzącym z klastra: możesz postawić klaster w trybie UDR (user defined routing) tak by każdy pakiet najpierw trafiał w jakiś egress firewall (np. w hubie przy użyciu hub&spoke), gdzie dodatkowo możesz filtrować ruch
