### DISCUSSION TITLE
[GitHub Actions] Wywołanie zewnętrznego skryptów Inline, a obsługa błędów

### DISCUSSION THREAD

**Discussion by sbugalski** [AzureCommunityPL/group#353] [Pomoc]
Cześć,

Głowię się i binguję nad tym w jaki sposób wywołać obsługi błędów w GitHub Actions dla zewnętrznych skryptów (nie inline) uruchamianych w akcjach [azure/powershell](https://github.com/Azure/powershell).

W przypadku wystąpienia błędu w skrypcie Az-Script.ps1, pomimo ustawienia w skrypcie try catch, ErrorActionPreference=stop, kodów wyjścia task wykonuje się poprawnie

W jaki sposób to rozwiązujecie u siebie?

```yaml
- name: Run Az script with pwsh
  uses: azure/powershell@v1
  with: 
    inlineScript: |
      pwsh -File ./scripts/Az-Script.ps1
  failOnStandardError: true
```
