### DISCUSSION TITLE
Docker na app serivce plan - nie podmienia kontenera

### DISCUSSION THREAD

**Discussion by szympulka** [AzureCommunityPL/group#374] [Pomoc]
Hej, 

Mam problem z obrazem dokera. Mam postawionego lokalnie agenta gdzie buduje cały projekt i pcham do chmury. Nie wiem czemu, ale app service plan chociaż widzi zmiany z ostatniego pipeline to te zmiany nie są widoczne. Jeżeli usunę app service i postawie na nowo, to wtedy łyka poprawnie kontener. Zastanawiam się w którym momencie popełniłem błąd. Jakieś sugestie? 

YAML z pipeline

```
- stage: Deploy_ClientApi
  displayName: 'Deploy ClientApi'
  dependsOn: 
  - Build_Functions
  condition: and(succeeded(), and(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'), ne(variables['Build.Reason'], 'PullRequest')))
  jobs: 
  - deployment: Deploy
    environment: "Prod_ClientApi"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@2
            displayName: buildAndPush ClientApi
            inputs:
              command: 'buildAndPush'
              containerRegistry: 'xxxxxx001'
              repository:xxxxxxxClientApi
              Dockerfile: $(Build.Repository.LocalPath)/backend/Dockerfile
              tags: $(Build.BuildId)
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: 
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription'
              appType: webAppContainer
              WebAppName: 'xxxx-prod-weu-001'
              DockerNamespace: xxxxx.azurecr.io
              DockerRepository: xxxClientApi
              DockerImageTag: $(Build.BuildId)
```
