### DISCUSSION TITLE
Redirect dla Aplication Gateway zintegrowany z AKS

### DISCUSSION THREAD

**Discussion by KrzysztofDC** [AzureCommunityPL/group#479] [Pomoc]
cześć

Chciałbym zrobić prostą wydawałoby sie rzecz - redirect na aplication gateway zintegrowanym z AKS. Oczywiście taka opcja istnieje na app gateway, ale ja potrzebuje ją opisać w manifeście. Niestety nic takiego nie znajduje  dla app gateway + AKS (Ingress)
https://mojadomena.pl/costam/costam.pdf na https://costam.mojadomena.pl/costam/costam.pdf. dla aplication gateway + AKS, znalazłem tylko Rewrite Rule Set, ale tam, nie odść, że mogę tylko wskazać ręcznie przygotowany wcześniej rewrite, to mozna tylko patch i stringa zmienić.

**Comment by PawelHaracz** [comment]
Nie wiem czy dobrze zrozumiałem. Korzystasz w aks z application gateway ingress controller? Jak rozumiem potrzebujesz zrobisz redirect na inna subdomain. Nie kojarzę aby to było możliwe z poziomu ingress controllera, ale zawsze możesz zrobić route na inna domene. Wystarczy stworzyć service z externalName:
```yaml

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: myexternal.http.service.com
---
apiVersion: networking.k8s.io/v1 
kind: Ingres
metadata:
  name: externalNameservice
  namespace: prod
spec:
  rules:
  - host: service.example.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /
```
https://kubernetes.io/docs/concepts/services-networking/service/#externalname
