### DISCUSSION TITLE
[ARM Template, Azure Pipelines] Problem z przekazaniem parametru typu array przez plik z parametrami

### DISCUSSION THREAD

**Discussion by KamilWiecek** [AzureCommunityPL/group#91] [Pomoc] [answered]
Hej, z góry dzięki za pomoc.

Mój scenariusz:
-	Robię deployment przy użyciu Azure Pipelines
-	Scope to Management Groupa
-	Używam taska AzurePowershell@5 (New-AzManagementGroupDeployment …)
-	Plik z parametrami wygląda tak:

``` json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "param1": {
            "value": [
                "a",
                "b"
            ]
        }
    }
}
```

Deployment z mojej stacji kończy się sukcesem. 
Deployment z poziomu pipeline kończy się błędem (używam tego samego tempalteFile i tego samego templateParametersFile).

W portalu w *deployments* podglądam plik z parametrami to wygląda on tak:

``` json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "param1": {
            "value": [
                [],
                []
            ]
        }
    }
}
```

I faktycznie, błąd potwierdza to co widać:
```
The expected policy parameter type: 'String'. The actual policy parameter type 'Array'
```

Mam już obejście. Gdy ustawię z samym ARM Template "defaultValue" i nie ustawię wartości parametru w pliki z parametrami, to działa. Działa też gdy przekażę te same parametry jako ParametersObject.

Oznacza to, że ze stringów w array robią się array i zamiast tablicy stringów mam tablicę tablic, ale tylko z poziomu pipeline i tylko gdy korzysta się z pliku z parametrami. 

Podejrzewam, że to coś po stronie agenta (wersja Az, PS, ...), ale kolejne testy są dość czasochłonne. Macie jakieś sugestie?

**Comment by kamil-mrzyglod** [comment]
Pokaż nam jak przekazujesz parametr w Azure DevOps.

**Comment by KamilWiecek** [comment]
Fragment skryptu:

``` powershell

$deploymentParameters = @{
    ManagementGroupId     = ...
    Name                  = ...
    TemplateFile          = ...
    TemplateParameterFile = ...
    Location              = ...
}

New-AzManagementGroupDeployment @deploymentParameters -Confirm:$false -ErrorAction Stop
```

**Reply by kamil-mrzyglod** [reply]
No okej - ale skąd się biorą parametry przekazane do szablonu? Przekazujesz je za pomocą `TemplateParameterFile` czy jeszcze jakoś inaczej?

**Reply by KamilWiecek** [reply]
Na czas testów uprościłem to już do takiej postaci:

``` yaml
trigger:
- ###

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '###'
    ScriptType: 'InlineScript'
    Inline: 
      $location = '###'

      $deploymentParameters = @{
        ManagementGroupId     = '###';
        TemplateFile          = './template.json';
        TemplateParameterFile = './parameters.json';
        Location              = $location
      }

      New-AzManagementGroupDeployment @deploymentParameters -Confirm:$false -ErrorAction Stop
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true


````

**Comment by KamilWiecek** [comment, marked as answer]
Zadziałało po wskazaniu wersji AzurePowerShell:

```
azurePowerShellVersion: OtherVersion
preferredAzurePowerShellVersion: 4.4.0
```

Całość:

``` yaml
- ###

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: '###'
    ScriptType: 'InlineScript'
    Inline: 
      $location = '###'

      $deploymentParameters = @{
        ManagementGroupId     = '###';
        TemplateFile          = './template.json';
        TemplateParameterFile = './parameters.json';
        Location              = $location
      }

      New-AzManagementGroupDeployment @deploymentParameters -Confirm:$false -ErrorAction Stop
    azurePowerShellVersion: OtherVersion
    preferredAzurePowerShellVersion: 4.4.0
    pwsh: true

````

**Podsumowując:**
- Root cause to moduł Az.Resources
- Jeżeli
    - wdrażasz ARM Template Powershellem 
    - korzystasz z hosted agent
    - parametry przekazujesz przez plik
    - przekazujesz wartość parametru typu array
- To:
    - wskaż konkretną wersją Azure Powershell:
```
azurePowerShellVersion: OtherVersion
preferredAzurePowerShellVersion: 4.4.0
```


Jest już na to założone issue:
[https://github.com/Azure/azure-powershell/issues/12835](https://github.com/Azure/azure-powershell/issues/12835)
