### DISCUSSION TITLE
CD yaml + docker compose

### DISCUSSION THREAD

**Discussion by szympulka** [AzureCommunityPL/group#97] [Pomoc]
Próbuję zrobić automatyzację wrzucania kontenera na środowisko i odpalania go.  Wyklepałem sobie yamla z dwma stage. Jeden to build i pcham obraz do acr, a drugi to już operacja na maszynie. Wrzuciłem docelową maszynę do environments. Próbuję zrobić pull obrazów, lecz dostaję info, że nie może znaleźć pliku.  Wrzucam go do artefaktu. Czy plik ten powinien być na maszynie, czy jak to jest?

```yaml
name: $(Date:yyyyMMdd)$(Rev:.r)
pool:
  name: UbuntuAgent
  demands: npm
stages:
- stage: Build   
  jobs:
  - job: Buid
    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: Frontend
        verbose: false

    - task: Npm@1
      displayName: 'npm build'
      inputs:
        command: custom
        workingDir: Frontend
        verbose: false
        customCommand: 'run build'

    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 
        repository: si
        tags: dev

    - task: CmdLine@2
      displayName: ef migrations
      inputs:
        script: |
          export PATH="$PATH:$HOME/.dotnet/tools/"
                dotnet ef migrations script --idempotent -o $(Build.ArtifactStagingDirectory)/db.sql
        workingDirectory: 'Backend/Applications/Web'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: Scripts/docker/Dev
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      
- stage: CD   
  jobs:
  - deployment: deploy
    environment: dev
    strategy:
      runOnce:  
        deploy:
          steps:
          - task: Docker@2
            inputs:
              containerRegistry: ''
              command: 'login'
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: '[Dev] (-beb6-408c--)'
              azureContainerRegistry: '{"loginServer":".azurecr.io", "id" : "/subscriptions/-beb6-408c--///providers/Microsoft.ContainerRegistry/registries/"}'
              dockerComposeFile: '**/docker-compose.yml'
              projectName: 'dev'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'pull'
              currentWorkingDirectory: '$(Build.ArtifactStagingDirectory)'
```

**Comment by kaluzaaa** [comment]
@szympulka na przyszłość użyj **\`\`\`** do wystawienia bloku kodu i typu jeśli to jakiś popularny format to wskazania na starcie np tak jak tu **\`\`\`yaml**. W końcu po to jesteśmy na gh nie fb ;-)

https://guides.github.com/features/mastering-markdown/

**Reply by szympulka** [reply]
Dzięki za poprawkę 👍

**Comment by kamil-mrzyglod** [comment]
Pierwsza rzecz - nie do końca wiadomo o jaki plik chodzi. Zakładam, że masz na myśli `docker-compose.yml`?

Druga rzecz - nie mam pewności czy `dockerComposeFile: '**/docker-compose.yml'` znajdzie tego YAMLa, który tak na oko znajduje się w katalogu `Scripts/docker/Dev`.

Trzecia rzecz - dodaj jeden krok przed Docker Compose i wylistuj pliki jakie masz dostępne na agencie. Upewnij się też, że Twój drugi stage robi automatycznie download artefaktów(i są to dobre artefakty).

**Reply by kmadof** [reply]
Tak jak @kamil-mrzyglod napisał. Pobierz sobie artefakty w `CD` stage'u. Bardzo możliwe, że je tam masz bo używasz self hosted agent, jednak w dłuższej perspektywie to mozę dopraowadzić do problemów. Tutaj masz urla co do [downloadów](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml).  Z tego co widzę to korzystasz ze starszego taska `PublishBuildArtifacts@1`. Wszystko z nim jest ok, ale możesz też rozważyć zmianę na tego [taska](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)

**Reply by szympulka** [reply]
Zauważyłem taki problem, że choć mam falgę environment to całość jest odpalana na agencie. Czy nie powinien on tych tasków robić na agencie?

**Reply by szympulka** [reply]
Jeżeli dobrze rozumiem to task docker-compose odpalamy na docelowej maszynie. Stąd też stworzyłem environment, na którym ma się odpalać doker

**Reply by kamil-mrzyglod** [reply]
@szympulka - no okej ale jak to ma się do samego problemu? Masz stage Build i stage CD. One nie współdzielą artefaktów. Dodatkowo masz environment, który jak rozumiem skonfigurowałeś tak, że masz tam podpiętą VM. To jest ta sama maszyna co pula UbuntuAgent?

> Zauważyłem taki problem, że choć mam falgę environment to całość jest odpalana na agencie. Czy nie powinien on tych tasków robić na agencie?

Trochę masło maślane ;)

**Reply by szympulka** [reply]
Faktycznie masło maślane, źle przekazałem swoją myśl, przepraszam. Mam UbuntuAgenta, który jest self hosted agentem w organizacji. Używają go różne projekty. Maszyna developerska jest oddzielona i dodana do Environments w piepline. Odpalając konsole i "ls" w CD dostałem strukturę katalogu z UbuntuAgenta. Artefakty, które są kopiowane lądują również w katalogu agenta(rozpoznaje po nazwie użytkownika w ścieżce). Z jednej strony mam info, że leci do na środowisku, a z drugiej pliki lądują gdzieś indziej.

![image](https://user-images.githubusercontent.com/12598823/95171438-29b37080-07b6-11eb-8cc2-54bb6c3343a1.png)

**Reply by kamil-mrzyglod** [reply]
Powiem tak - środowisk na czynniki pierwsze nie rozkładałem, ale czy przypadkiem używanie VM jak zasobu w `Environment`(podobnie jak k8s) nie oznacza, że to jest Twój docelowy target deploymentu, tj. tam lądują artefakty z aplikacji? Wydaje mi się, że to nie jest jednoznaczne z użyciem tej konkretnej VM jako agenta, szczególnie że agenta dziedziczysz od góry po ustawieniu parametru `pool` dla całego pipeline.

Po drugie jak spojrzysz na dokumentację:
```
jobs:  
- deployment: VMDeploy
  displayName: web
  environment:
    name:  VMenv
    resourceType: VirtualMachine
    tags: web1
  strategy:
```
Widać, że powinieneś konkretnie odnieść się do tej konkretnej maszyny. Tak czy siak ja obstawiam, że pokręciłeś nieco koncepty i użycie VM w środowisku nie oznacza użycia tej VM jako agenta dla jobów w deploymencie ;)
